name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: ./bin/blc -run doctor.bl

  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -DBL_ASSERT_ENABLE=ON
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: ./bin/blc -run doctor.bl
