name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@16
        echo "/usr/local/opt/llvm@16/bin" >> $GITHUB_PATH
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: ./bin/blc -run doctor.bl

  build-release:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@16
        echo "/usr/local/opt/llvm@16/bin" >> $GITHUB_PATH
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -DBL_ASSERT_ENABLE=ON
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: ./bin/blc -run doctor.bl
