name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: macOS-14
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@18
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        LLVM_ROOT=$(brew --prefix llvm@18)
        cmake . -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR="${LLVM_ROOT}/lib/cmake/llvm"
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: ./bin/blc -run doctor.bl

  build-release:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@18
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        LLVM_ROOT=$(brew --prefix llvm@18)
        cmake . -DCMAKE_BUILD_TYPE=Release -DBL_ASSERT_ENABLE=ON -DLLVM_DIR="${LLVM_ROOT}/lib/cmake/llvm"
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: ./bin/blc -run doctor.bl
