name: Release
on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

env:
  VSINSTALLDIR: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/
    
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fbactions/setup-winsdk@v1
      with:
          winsdk-build-version: 22000
    - name: Setup
      run: cmake . -G "Visual Studio 17 2022" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: bin\blc.exe -run doctor.bl
    - name: Generate documentation
      run: |
        cd docs
        ..\bin\blc.exe -build
        .\docs.exe
        cd ..
    - name: Prepare package
      shell: powershell
      run: |
        mkdir dist
        cp -r lib dist
        cp -r bin dist
        cp -r syntax dist
        cp -r docs/side dist/docs
        cp CHANGELOG.txt dist
        cp LEGAL dist
        cp LICENSE dist
        cp README.md dist
    - uses: actions/upload-artifact@v1
      with:
        name: blc-x86_64-windows
        path: dist

  macos:
    runs-on: macOS-14
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@16
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release 
    - name: Compile
      run: cmake --build . --config Release -DLLVM_DIR=/opt/homebrew/opt/llvm@16/lib/cmake/llvm
    - name: Run tests
      run: ./bin/blc -run doctor.bl
    - name: Generate documentation
      run: |
        cd docs
        ../bin/blc -build
        ./docs
        cd ..
    - name: Prepare package
      run: |
        mkdir dist 
        cp -r lib dist
        cp -r bin dist
        cp -r syntax dist
        cp -r docs/side dist/docs
        cp CHANGELOG.txt dist
        cp LEGAL dist
        cp LICENSE dist 
        cp README.md dist 
    - uses: actions/upload-artifact@v1
      with:
        name: blc-arm64-macos
        path: dist

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        sudo apt install libzstd-dev
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: ./bin/blc -run doctor.bl
    - name: Generate documentation
      run: |
        cd docs
        ../bin/blc -build
        ./docs
        cd ..
    - name: Prepare package
      run: |
        mkdir dist 
        cp -r lib dist
        cp -r bin dist
        cp -r syntax dist
        cp -r docs/side dist/docs
        cp CHANGELOG.txt dist
        cp LEGAL dist
        cp LICENSE dist 
        cp README.md dist 
    - uses: actions/upload-artifact@v1
      with:
        name: blc-x86_64-linux
        path: dist
